name: Deploy

on:
  workflow_run:
    workflows:
      - Laravel Pint
    types:
      - completed
  release:
    types:
      - published

jobs:
  deploy:
    runs-on: ubuntu-latest

    environment: ${{ github.event_name == 'workflow_run' && 'staging' || 'production' }}

    steps:
      - name: Deploy to Forge
        env:
          DEPLOY_URL: ${{ vars.DEPLOY_URL }}
        run: |
          if [ -z "$DEPLOY_URL" ]; then
            echo "Error: DEPLOY_URL is not set"
            exit 1
          fi
          curl "$DEPLOY_URL"
        shell: bash